token = "7fb179c2b6469b8937aa5bd94f639f47b33c67565b4750f3e6023f8b25addefcbc83a41ce0b55cf0d35cb" # 孝芯泻械薪 芯芯斜械胁邪 芯薪邪泻械

buttons_text = "vkbot.ru"
message_text = "@all
 蝎!
校效楔携 校  校小校 https://vk.com/raidersbot
校小 孝 https://vk.com/gud_com
小携 孝携 校 https://vk.com/gud_com_news
孝孝效小 孝 小蝎 孝蝎!
啸  校校  小 小啸 小 !
ㄢ┾ㄢ葛ご梆さ拣ぐううしし答吼垛娥○拣娥ぃ吼ぁ桂ｐゐ○娥ю拆叼仇别梆ヰい答ぅあぇ佛筐桂吼火金攫吼葛桂火拣金筐攫こゐｐｐヰ娥ю扁别答叼拆斥仇封佛碘叼┾ㄢ┾攫ㄢ攫┾仇ㄢ仇┾ㄢ┾ゐㄢゐ┾ㄢ┾ㄢ┾火ㄢ火┾拣ㄢ拣┾юㄢю┾ㄢ┾ㄢ┾ㄢ┾ㄢ┾ㄢ┾ㄢ葛ご梆さ拣ぐううしし答吼垛娥○拣娥

 " # 孝械泻 芯芯斜械薪懈. 谢懈 泻芯芯械 4096 斜邪泄芯胁 - 斜写械 锌芯胁芯薪 屑邪泻懈屑邪谢薪芯械 泻芯谢懈械胁芯 邪蟹

logging_level = "DEBUG"
delay = 0.33
